- name: Setup Archlinux Sway
  hosts: localhost
  pre_tasks:
    - name: Update and upgrade repositories
      become: true
      community.general.pacman:
        update_cache: true
        upgrade: true
  tasks:
    - name: Core
      include_tasks: tasks/core.yml
      tags: [ always, core ]
    - name: Pulseaudio
      include_tasks: tasks/pulse.yml
      tags: [ always, pulse ]
    - name: AMD
      include_tasks: tasks/amd.yml
      tags: [ never, amd ]
    - name: Intel
      include_tasks: tasks/intel.yml
      tags: [ never, intel ]
    - name: Git
      include_tasks: tasks/git.yml
      tags: [ always, git ]
    - name: Yay
      include_tasks: tasks/yay.yml
      tags: [ always, yay ]
    - name: Sway
      include_tasks: tasks/sway.yml
      tags: [ always, sway ]
    - name: Docker
      include_tasks: tasks/docker.yml
      tags: [ always, docker ]
    - name: Bluetooth
      include_tasks: tasks/bluetooth.yml
      tags: [ always, bluetooth ]
    - name: Dotfiles
      include_tasks: tasks/dotfiles.yml
      tags: [ always, dotfiles ]
    - name: Zsh
      include_tasks: tasks/zsh.yml
      tags: [ always, zsh ]
    - name: Devtools
      include_tasks: tasks/devtools.yml
      tags: [ always, devtools ]
    - name: Kubernetes
      include_tasks: tasks/kubernetes.yml
      tags: [ always, kubernetes ]
    - name: Gaming
      include_tasks: tasks/gaming.yml
      tags: [ never, gaming ]
