- name: Setup Archlinux Sway
  hosts: localhost
  pre_tasks:
    - name: Update and upgrade repositories
      become: true
      community.general.pacman:
        update_cache: true
        upgrade: true
  tasks:
    - name: Core
      include_tasks: tasks/core.yml
      tags: core
    - name: AMD
      include_tasks: tasks/amd.yml
      tags: amd
    - name: Intel
      include_tasks: tasks/intel.yml
      tags: intel
    - name: Git
      include_tasks: tasks/git.yml
      tags: git
    - name: Yay
      include_tasks: tasks/yay.yml
      tags: yay
    - name: Sway
      include_tasks: tasks/sway.yml
      tags: sway
    - name: Fprint
      include_tasks: tasks/fprint.yml
      tags: fprint
    - name: Docker
      include_tasks: tasks/docker.yml
      tags: docker
    - name: Bluetooth
      include_tasks: tasks/bluetooth.yml
      tags: bluetooth
    - name: Dotfiles
      include_tasks: tasks/dotfiles.yml
      tags: dotfiles
    - name: Zsh
      include_tasks: tasks/zsh.yml
      tags: zsh
    - name: Devtools
      include_tasks: tasks/devtools.yml
      tags: devtools
    - name: Kubernetes
      include_tasks: tasks/kubernetes.yml
      tags: kubernetes
    - name: Arduino
      include_tasks: tasks/arduino.yml
      tags: arduino
    - name: Gaming
      include_tasks: tasks/gaming.yml
      tags: gaming
