- name: Setup Archlinux Sway
  hosts: localhost
  pre_tasks:
    - name: Update and upgrade repositories
      become: true
      community.general.pacman:
        update_cache: true
        upgrade: true
      tags:
        - install
  tasks:
    - name: Core
      include: tasks/core.yml
    - name: Yay
      include: tasks/yay.yml
    - name: Sway
      include: tasks/sway.yml
    - name: Docker
      include: tasks/docker.yml
    - name: Bluetooth
      include: tasks/bluetooth.yml
    - name: Dotfiles
      include: tasks/dotfiles.yml
    - name: Zsh
      include: tasks/zsh.yml
    - name: Devtools
      include: tasks/devtools.yml
