- name: Setup Archlinux Sway
  hosts: localhost
  become: true
  pre_tasks:
    - name: Pacman update and upgrade
      community.general.pacman:
        update_cache: true
        upgrade: true
  tasks:
    - include: tasks/sway.yml
    - include: tasks/yay.yml
    - include: tasks/docker.yml
    - include: tasks/bluetooth.yml
    - include: tasks/devtools.yml
    - include: tasks/productivity.yml
    - include: tasks/dotfile.yml
