- name: Install AMD drivers
  community.general.pacman:
    name:
      - lib32-mesa
      - vulkan-radeon
      - lib32-vulkan-radeon
      - vulkan-icd-loader
      - lib32-vulkan-icd-loader
    extra_args: --needed
  tags: amd
