- name: Bluetooth
  community.general.pacman:
    name:
      - bluez
      - bluez-utils
  tags:
    - install
    - bluetooth

- name: Enable bluetooth service
  command: systemctl enable --now bluetooth
  tags:
    - install
    - bluetooth
