- name: Install bluetooth dependencies
  community.general.pacman:
    name:
      - blueman
      - bluez
      - bluez-utils
- name: Enable bluetooth service
  command: systemctl enable --now bluetooth
