- name: Bluetooth
  become: true
  community.general.pacman:
    name:
      - bluez
      - bluez-utils
  tags: bluetooth

- name: Enable bluetooth service
  become: true
  command: systemctl enable --now bluetooth
  tags: bluetooth
