- name: Bluetooth
  become: true
  community.general.pacman:
    name:
      - bluez
      - bluez-utils
  tags:
    - install
    - bluetooth

- name: Enable bluetooth service
  become: true
  command: systemctl enable --now bluetooth
  tags:
    - install
    - bluetooth
