- name: Install core packages
  community.general.pacman:
    name:
      - networkmanager
      - core/make
      - core/patch
      - core/gcc
      - core/autoconf
      - core/automake
      - core/binutils
      - core/bison
      - core/fakeroot
      - htop
  become: true

- name: Enable NetworkManager
  command: systemctl enable --now NetworkManager
  become: true
