- name: Install core packages
  community.general.pacman:
    name:
      - networkmanager
      - core/make
      - core/patch
      - core/gcc
      - core/autoconf
      - core/automake
      - core/binutils
      - core/bison
      - core/fakeroot
  become: true
  tags:
    - install
    - core
- name: Enable NetworkManager
  command: systemctl enable NetworkManager
  become: true
  tags:
    - install
    - core
