- name: Install core packages
  community.general.pacman:
    name:
      - NetworkManager
  become: true
  tags:
    - core
- name: Enable NetworkManager
  command: systemctl enable --now NetworkManager
  become: true
  tags:
    - core
