- name: Install dev tools
  become: true
  community.general.pacman:
    name:
      - go
      - rust
      - cargo
      - neovim
      - minikube
      - tmux
      - postgresql
  tags:
    - install
    - dev
