- name: Install docker
  community.general.pacman:
    name:
      - docker
      - docker-buildx
      - docker-compose
  tags:
    - install
    - docker

- name: Add user to docker group
  ansible.builtin.user:
    name: testuser
    shell: /bin/bash
    groups: docker
    append: yes
  tags:
    - install
    - docker

- name: Start docker service
  shell: systemctl enable docker
  tags:
    - install
    - docker
