- name: Install docker
  community.general.pacman:
    name:
      - docker
        docker-buildx
        docker-compose
- name: Add user to docker group
  user:
    - name: "{{ system.username }}"
      groups: docker
      append: yes

- name: Start docker service
  shell: systemctl enable docker
