- name: Install stow
  become: true
  community.general.pacman:
    name: stow

- name: Clone dotfiles
  ansible.builtin.git:
    repo: https://github.com/gKits/.dotfiles
    dest: $HOME/.dotfiles
    recursive: yes
    update: yes
    accept_hostkey: yes
    version: main

- name: Stow dotfiles
  shell: cd $HOME/.dotfiles && ./install
