- name: Install stow
  apt:
    name: stow
  tags:
    - install
    - dotfiles

- name: Clone dotfiles
  ansible.builtin.git:
    repo: 'git@github.com/gKits/.dotfiles.git'
    dest: "{{ lookup('env', 'HOME') }}/.dotfiles"
    recursive: yes
    update: yes
    accept_hostkey: yes
    version: main
  tags:
    - install
    - dotfiles

- name: Stow dotfiles
  shell: cd $HOME/.dotfiles && ./install
  tags:
    - install
    - dotfiles
