- name: Install git
  become: true
  community.general.pacman:
    name:
      - git
      - github-cli

- name: Git personal setup email
  git_config:
    name: user.email
    scope: global
    value: "gkitsikoudis@gmx.de"

- name: Git personal setup name
  git_config:
    name: user.name
    scope: global
    value: "gKits"
