- name: Install Intel drivers
  community.general.pacman:
    name:
      - lib32-mesa
      - vulkan-intel
      - lib32-vulkan-intel
      - vulkan-icd-loader
      - lib32-vulkan-icd-loader
    extra_args: --needed
  tags: intel
