- name: Install Sway window manager
  become: true
  community.general.pacman:
    name:
      - sway
      - swayidle
      - swaylock
      - swaybg
      - waybar
      - wl-clipboard
  tags: sway

- name: Install XWayland clients
  become: true
  community.general.pacman:
    name:
      - xorg-xwayland
      - xorg-xlsclients
      - qt5-wayland
      - glfw-wayland
  tags: sway

- name: Install alacritty terminal emulator
  become: true
  community.general.pacman:
    name: alacritty
  tags: sway

- name: Install mako notification daemon
  become: true
  community.general.pacman:
    name: mako
  tags: sway

- name: Install ranger terminal file manager
  become: true
  community.general.pacman:
    name: ranger
  tags: sway

- name: Install sway-launcher-desktop fzf application launcher
  kewlfft.aur.aur:
    use: yay
    name:
      - sway-launcher-desktop 
  tags: sway

- name: Install wlay display server GUI
  kewlfft.aur.aur:
    use: yay
    name:
      - wlay-git
  tags: sway

- name: Install clipman clipboard manager
  kewlfft.aur.aur:
    use: yay
    name:
      - clipman
  tags: sway

- name: Install lemurs display/login manager
  kewlfft.aur.aur:
    use: yay
    name:
      - lemurs-git
  tags: sway

- name: Create directory for sway lemurs config
  become: true
  file:
    path: "/etc/lemurs/wayland/"
    state: directory
    owner: root
    mode: u=rwx,g=rwx,o=rx
    recurse: true
  tags: sway

- name: Create sway session startup script for lemurs
  become: true
  copy:
    dest: "/etc/lemurs/wayland/sway"
    content: |
      #! /bin/sh
      set -a
      [ -f $HOME/.config/sway/env ] && . "$HOME/.config/sway/env"
      set +a
      exec sway
    mode: u=rwx,g=rx,o=rx
    owner: root
  tags: sway

- name: Add user to seat group for starting session with lemurs
  become: true
  ansible.builtin.user:
    name: "{{ ansible_user_id }}"
    shell: /bin/bash
    groups: seat
    append: yes
  tags: sway

- name: Enable lemurs service
  become: true
  shell: systemctl enable lemurs
  tags: sway

- name: Install graphical network/bluetooth tools
  become: true
  community.general.pacman:
    name:
      - blueman
      - network-manager-applet
  tags: sway

- name: Install screenshot tools
  become: true
  community.general.pacman:
    name:
      - grim
      - slurp
  tags: sway

- name: Install dependencies to allow screensharing
  become: true
  community.general.pacman:
    name:
      - xdg-desktop-portal-wlr
      - xdg-desktop-portal
  tags: sway

- name: Install light for brightness control
  become: true
  community.general.pacman:
    name: light
  tags: sway
