- name: Sway WM
  become: true
  community.general.pacman:
    name:
      - sway
      - swayidle
      - swaylock
      - swaybg
      - waybar
      - wofi
      - alacritty
      - wl-clipboard
      - ranger
  tags:
    - install
    - sway

- name: XWayland
  become: true
  community.general.pacman:
    name:
      - xorg-xwayland
      - xorg-xlsclients
      - qt5-wayland
      - glfw-wayland
  tags:
    - install
    - sway

- name: Display server GUI
  kewlfft.aur.aur:
    use: yay
    name:
      - wlay-git
  become: yes
  become_user: aur_builder
  tags:
    - install
    - sway

- name: Clipboard manager
  kewlfft.aur.aur:
    use: yay
    name:
      - clipman
  become: yes
  become_user: aur_builder
  tags:
    - install
    - sway

- name: Lemurs DM
  kewlfft.aur.aur:
    use: yay
    name:
      - lemurs-git
  become: yes
  become_user: aur_builder
  tags:
    - install
    - sway

- name: Network utils
  become: true
  community.general.pacman:
    name:
      - blueman
      - network-manager-applet
  tags:
    - install
    - sway

- name: Screenshots
  become: true
  community.general.pacman:
    name:
      - grim
      - slurp

- name: Screensharing
  become: true
  community.general.pacman:
    name:
      - xdg-desktop-portal-wlr
      - xdg-desktop-portal
  tags:
    - install
    - sway
