- name: Install Sway window manager
  become: true
  community.general.pacman:
    name:
      - sway
      - swayidle
      - swaylock
      - swaybg
      - waybar
      - wofi
      - alacritty
      - wl-clipboard
      - ranger
  tags:
    - install
    - sway

- name: Install XWayland clients
  become: true
  community.general.pacman:
    name:
      - xorg-xwayland
      - xorg-xlsclients
      - qt5-wayland
      - glfw-wayland
  tags:
    - install
    - sway

- name: Install wlay display server GUI
  kewlfft.aur.aur:
    use: yay
    name:
      - wlay-git
  become: yes
  become_user: aur_builder
  tags:
    - install
    - sway

- name: Install Clipboard manager
  kewlfft.aur.aur:
    use: yay
    name:
      - clipman
  tags:
    - install
    - sway

- name: Install Lemurs Display/Login manager
  kewlfft.aur.aur:
    use: yay
    name:
      - lemurs-git
  tags:
    - install
    - sway

- name: Create Sway session startup script for Lemurs
  become: true
  copy:
    dest: "/etc/lemurs/wayland/sway"
    content: |
      #! /bin/sh
      exec sway
    mode: u=rwx,g=rx,o=rx
    owner: root
  tags:
    - install
    - sway

- name: Add user to seat group for starting session with Lemurs
  become: true
  ansible.builtin.user:
    name: {{ ansible_user_id }}
    shell: /bin/bash
    groups: seat
    append: yes
  tags:
    - install
    - sway

- name: Install graphical network tools
  become: true
  community.general.pacman:
    name:
      - blueman
      - network-manager-applet
  tags:
    - install
    - sway

- name: Install Screenshot tools
  become: true
  community.general.pacman:
    name:
      - grim
      - slurp

- name: Install dependencies to allow screensharing
  become: true
  community.general.pacman:
    name:
      - xdg-desktop-portal-wlr
      - xdg-desktop-portal
  tags:
    - install
    - sway
