- name: Install Sway window manager
  become: true
  community.general.pacman:
    name:
      - sway
      - swayidle
      - swaylock
      - swaybg
      - waybar
      - wofi
      - wl-clipboard

- name: Install XWayland clients
  become: true
  community.general.pacman:
    name:
      - xorg-xwayland
      - xorg-xlsclients
      - qt5-wayland
      - glfw-wayland

- name: Install alacritty terminal emulator
  become: true
  community.general.pacman:
    name: alacritty

- name: Install mako notification daemon
  become: true
  community.general.pacman:
    name: mako

- name: Install ranger terminal file manager
  become: true
  community.general.pacman:
    name: ranger

- name: Install wlay display server GUI
  kewlfft.aur.aur:
    use: yay
    name:
      - wlay-git

- name: Install clipman clipboard manager
  kewlfft.aur.aur:
    use: yay
    name:
      - clipman

- name: Install lemurs display/login manager
  kewlfft.aur.aur:
    use: yay
    name:
      - lemurs-git

- name: Create directory for sway lemurs config
  become: true
  file:
    path: "/etc/lemurs/wayland/"
    state: directory
    owner: root
    mode: u=rwx,g=rwx,o=rx
    recurse: true

- name: Create sway session startup script for lemurs
  become: true
  copy:
    dest: "/etc/lemurs/wayland/sway"
    content: |
      #! /bin/sh
      exec sway
    mode: u=rwx,g=rx,o=rx
    owner: root

- name: Add user to seat group for starting session with lemurs
  become: true
  ansible.builtin.user:
    name: "{{ ansible_user_id }}"
    shell: /bin/bash
    groups: seat
    append: yes

- name: Enable lemurs service
  become: true
  shell: systemctl enable lemurs

- name: Install graphical network/bluetooth tools
  become: true
  community.general.pacman:
    name:
      - blueman
      - network-manager-applet

- name: Install screenshot tools
  become: true
  community.general.pacman:
    name:
      - grim
      - slurp

- name: Install dependencies to allow screensharing
  become: true
  community.general.pacman:
    name:
      - xdg-desktop-portal-wlr
      - xdg-desktop-portal

- name: Install light for brightness control
  become: true
  community.general.pacman:
    name: light
