- name: Clone yay
  git:
    repo: https://aur.archlinux.org/yay.git
    dest: ~/yay
    update: true
- name: Build and install yay
  command:
    chdir: ~/yay
    cmd: makepkg -sfi --noconfirm
    creates: /usr/bin/yay
