- name: Install zsh
  become: true
  community.general.pacman:
    name:
      - zsh
  tags:
    - install
    - dotfiles
    - zsh

- name: Change default shell to zsh
  become: true
  shell: chsh -s $(which zsh)
  tags:
    - install
    - dotfiles
    - zsh
